function getData(){
	return [
		[{qustion: 1,answer: true},
		{qustion: 2,answer: true},
		{qustion: 3,answer: false},
		{qustion: 4,answer: true},
		{qustion: 5,answer: true},
		{qustion: 6,answer: true},
		{qustion: 7,answer: true},
		{qustion: 8,answer: true},
		{qustion: 9,answer: true},
		{qustion: 10,answer: true},
		{result: true}],
		[{qustion: 1,answer: true},
		{qustion: 2,answer: true},
		{qustion: 3,answer: true},
		{qustion: 4,answer: true},
		{qustion: 5,answer: true},
		{qustion: 6,answer: true},
		{qustion: 7,answer: true},
		{qustion: 8,answer: true},
		{qustion: 9,answer: true},
		{qustion: 10,answer: true},
		{result: false}],
		[{qustion: 1,answer: true},
		{qustion: 2,answer: true},
		{qustion: 3,answer: true},
		{qustion: 4,answer: true},
		{qustion: 5,answer: true},
		{qustion: 6,answer: true},
		{qustion: 7,answer: true},
		{qustion: 8,answer: true},
		{qustion: 9,answer: true},
		{qustion: 10,answer: true},
		{result: false}],
		[{qustion: 1,answer: true},
		{qustion: 2,answer: true},
		{qustion: 3,answer: true},
		{qustion: 4,answer: true},
		{qustion: 5,answer: true},
		{qustion: 6,answer: true},
		{qustion: 7,answer: true},
		{qustion: 8,answer: true},
		{qustion: 9,answer: true},
		{qustion: 10,answer: true},
		{result: true}],
		[{qustion: 1,answer: true},
		{qustion: 2,answer: true},
		{qustion: 3,answer: false},
		{qustion: 4,answer: true},
		{qustion: 5,answer: true},
		{qustion: 6,answer: false},
		{qustion: 7,answer: false},
		{qustion: 8,answer: true},
		{qustion: 9,answer: true},
		{qustion: 10,answer: true},		
		{result: true}]
	]
}
